Dockerfile, docker-entrypoint.d/40-generate-config.sh, helm/values.yaml, public/index.html, src/utils/axiosInstances.js
Signed-off-by: Dmitry Dunaev <dmitry@opsfleet.com>
=> [WIFI-7463] Chg: modify Docker runtime files to support new version

helm/values.yaml
Signed-off-by: Dmitry Dunaev <dmitry@opsfleet.com>
=> [WIFI-7825] Chg: use ClusterIP for service by default

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/CreateObjectsForms/LocationPickerCreator/Modal.js, src/components/CreateObjectsForms/LocationPickerCreator/index.js, src/components/Tables/LocationTable/CreateLocationModal/Form.js, src/components/Tables/LocationTable/EditLocationModal/Form.js, src/constants/countryList.ts, src/hooks/Network/Analytics.ts, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/RadiosSection/radiosConstants.js, src/pages/EntityPage/EntityChildrenCard/index.js, src/pages/MapPage/MapCard/MapDisplayCard/Map/index.js, src/pages/VenuePage/VenueChildrenCard/VenueDashboard/TableModal.js
- Additional fixes for: [WIFI-9467] [WIFI-9470] [WIFI-9595] [WIFI-9596]
[WIFI-9467]: https://telecominfraproject.atlassian.net/browse/WIFI-9467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIFI-9470]: https://telecominfraproject.atlassian.net/browse/WIFI-9470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIFI-9595]: https://telecominfraproject.atlassian.net/browse/WIFI-9595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIFI-9596]: https://telecominfraproject.atlassian.net/browse/WIFI-9596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WIFI-9466]: unable to add device and contact to root entity

src/pages/VenuePage/VenueCard/Form.js
- Single fix for both [WIFI-9472] [WIFI-9598]
[WIFI-9472]: https://telecominfraproject.atlassian.net/browse/WIFI-9472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIFI-9598]: https://telecominfraproject.atlassian.net/browse/WIFI-9598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Signed-off-by: Charles Bourque charles.bourque@arilia.com
=> [WIFI-9472] [WIFI-9598] Venue says error fetching analytics

src/constants/formSchemas.ts
Signed-off-by: Charles Bourque charles.bourque@arilia.com
=> [WIFI-9601] Now validating analytics board values within venue card

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/Tables/InventoryTable/ImportDeviceCsvModal/ImportDeviceFile/index.js, src/components/Tables/InventoryTable/ImportDeviceCsvModal/ImportDeviceTests/index.js, src/hooks/Network/Analytics.ts, src/pages/AccountPage/AccountCard/MfaSelectField/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/GlobalsSection/index.js, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/index.js, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/MetricsSection/index.js, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/RadiosSection/index.js, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/index.js, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/UnitSection/index.js, src/pages/SystemPage/SystemTile/index.tsx, src/pages/VenuePage/VenueCard/Form.js, src/pages/VenuePage/VenueChildrenCard/index.js
Signed-off-by: Charles Bourque <charles.bourque96@gmail.com>
Also contains fixes for: [WIFI-9564] [WIFI-9562] [WIFI-9558] [WIFI-9621]
[WIFI-9564]: https://telecominfraproject.atlassian.net/browse/WIFI-9564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIFI-9562]: https://telecominfraproject.atlassian.net/browse/WIFI-9562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIFI-9558]: https://telecominfraproject.atlassian.net/browse/WIFI-9558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WIFI-9621]: https://telecominfraproject.atlassian.net/browse/WIFI-9621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WIFI-9551] Venue analytics not loading/saving bad values

package-lock.json, package.json, src/pages/SystemPage/SystemTile/index.tsx
=> [WIFI-9744] System page now shows OWSEC

src/pages/VenuePage/VenueChildrenCard/VenueDashboard/Header/DeviceTypeStat.js
=> [WIFI-9789] Device types count fix in venue dashboard

src/pages/EntityPage/EntityCard/index.js, src/pages/VenuePage/VenueCard/index.tsx
=> [WIFI-9927] Removed duplicate create buttons on entity/venue page

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/pages/MapPage/MapCard/MapDisplayCard/CreateMapButton/Form.js, src/pages/MapPage/MapCard/MapDisplayCard/CreateMapButton/index.js
=> [WIFI-9925] Clarifying duplicating vs creating a map

package-lock.json, package.json, src/pages/VenuePage/VenueChildrenCard/VenueDashboard/index.js
=> [WIFI-10005] Average memory fix

src/hooks/Network/Entity.ts
=> [WIFI-9837] [WIFI-9839] : fixing display of contacts on sub-venues

package-lock.json, package.json, src/pages/VenuePage/VenueCard/Actions.tsx
=> [WIFI-10073] Venue upgrade all devices now working as expected

src/components/TableCells/DeviceActionDropdown/index.tsx, src/components/Tables/InventoryTable/EditTagModal/ActionDropdown.tsx, src/hooks/Network/GatewayDevices.ts, src/models/Device.ts
=> [WIFI-10243] Added connect command

src/hooks/Network/Endpoints.ts, src/hooks/Network/System.ts, src/pages/SystemPage/SystemTile/index.tsx, src/pages/SystemPage/index.tsx
=> [WIFI-10252] System page now using endpoints coming from ucentralsec

src/components/FormFields/NotesField/index.tsx, src/hooks/Network/Account.ts, src/models/Note.ts, src/models/User.ts, src/pages/AccountPage/AccountCard/Form.js, src/pages/AccountPage/AccountCard/index.js, src/pages/AccountPage/index.tsx
=> [WIFI-10270] Account page fixes including working delete avatar

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Rrm/Rrm.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-10287] RRM field schema fix, no longer requiring unnecessary values

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ViewJsonConfig/index.tsx
=> [WIFI-10535] Configuration JSON should not contain PROV-specific data

src/layout/Navbar/index.tsx
=> [WIFI-9560] Added back button to navbar

src/components/Modals/Resources/Sections/InterfaceSsidRadius/schemas.ts, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ViewJsonConfig/index.tsx
=> [WIFI-10248] Interface configuration schema fixes

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Tunnel/TunnelValues.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Tunnel/index.tsx
=> [WIFI-10538] Added dhcp-healthcheck to tunnel.gre

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/Ipv4.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV6/Ipv6.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV6/index.tsx
=> [WIFI-10537] Only downstream interfaces can have port-forward/traffic-allow

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/hooks/Network/System.ts, src/pages/SystemPage/index.tsx
=> [WIFI-10437] System error alerts clearer to user

src/pages/VenuePage/VenueCard/Form.js
=> [WIFI-10436] Enabled analytics creation when old board returns 404

src/pages/VenuePage/VenueChildrenCard/VenueDashboard/index.js
=> [WIFI-10554] Venue analytics displaying unrecognized firmware

src/components/Modals/Resources/Sections/InterfaceSsid/Form.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/SingleSsid.js
=> [WIFI-10472] Added 6G option to configuration ssid.wifi-bands

Dockerfile
Signed-off-by: Dmitry Dunaev <dmitry@opsfleet.com>
=> [WIFI-10414] Fix: vulnerable NodeJS image

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/AdvancedSettings.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Encryption/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/SingleSsid.js
=> [WIFI-10506] Multi-psk now unavailable when using SAE encryption proto

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/CustomFields/DeviceRulesField/index.tsx, src/components/CustomFields/RrmFormField/AlgorithmPicker.tsx, src/components/CustomFields/RrmFormField/Form.tsx, src/components/CustomFields/RrmFormField/Parameters.tsx, src/components/CustomFields/RrmFormField/ProviderPicker.tsx, src/components/CustomFields/RrmFormField/Scheduler.tsx, src/components/CustomFields/RrmFormField/helper.ts, src/components/CustomFields/RrmFormField/index.tsx, src/components/InfoPopover/index.tsx, src/components/Modals/Modal/index.tsx, src/contexts/AuthProvider/index.tsx, src/hooks/Network/Rrm.ts, src/hooks/Network/System.ts, src/utils/axiosInstances.ts
=> [WIFI-10672] Added custom RRM options

package-lock.json, package.json, src/components/CustomFields/RrmFormField/AlgorithmPicker.tsx, src/components/CustomFields/RrmFormField/Form.tsx, src/components/CustomFields/RrmFormField/ProviderPicker.tsx, src/components/CustomFields/RrmFormField/Scheduler.tsx, src/components/CustomFields/RrmFormField/helper.ts, src/components/CustomFields/RrmFormField/index.tsx, src/components/Tables/InventoryTable/EditTagModal/Form.js, src/constants/formSchemas.ts, src/pages/VenuePage/VenueCard/Form.js, src/utils/dateFormatting.ts
=> [WIFI-10672] New RRM format using object instead of string

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/CustomFields/ConfigurationResourcePicker/ResourcePicker.js, src/components/Modals/Resources/CreateModal/index.tsx, src/components/Modals/Resources/EditModal/index.tsx, src/components/Modals/Resources/Sections/CaptivePortal/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Captive/Captive.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Captive/LockedCaptive.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Captive/index.tsx
=> [WIFI-10815] Captive Portal resource

src/components/Modals/Resources/CreateModal/index.tsx, src/components/Modals/Resources/EditModal/index.tsx, src/components/Modals/Resources/Sections/Tunnel/Form.tsx, src/components/Modals/Resources/Sections/Tunnel/index.tsx, src/models/ConfigurationSections/Interfaces.ts, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Tunnel/LockedTunnel.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Tunnel/Tunnel.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Tunnel/TunnelValues.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Tunnel/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ViewJsonConfig/useInterfacesJsonDisplay.ts
=> [WIFI-10816] Interface tunnel resource

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json
=> [WIFI-10082] Adjusted venue upgrade notification labels

src/components/Modals/Resources/CreateModal/index.tsx, src/components/Modals/Resources/EditModal/index.tsx, src/components/Modals/Resources/Sections/Ipv4/Form.tsx, src/components/Modals/Resources/Sections/Ipv4/index.tsx, src/models/ConfigurationSections/Interfaces.ts, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/DhcpIpV4.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/DhcpLeaseIpV4.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/Ipv4.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/LockedIpv4.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/StaticIpV4.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/IpV4/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/Tunnel/LockedTunnel.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ViewJsonConfig/useInterfacesJsonDisplay.ts
=> [WIFI-10817] Added ipv4 resource

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/CustomFields/RrmFormField/AlgorithmPicker.tsx, src/components/CustomFields/RrmFormField/Algorithms.tsx, src/components/CustomFields/RrmFormField/Form.tsx, src/components/CustomFields/RrmFormField/ProviderPicker.tsx, src/components/CustomFields/RrmFormField/Scheduler.tsx, src/components/CustomFields/RrmFormField/index.tsx, src/components/InfoPopover/index.tsx
=> [WIFI-10835] Now allowing for multiple RRM algorithms

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/AdvancedSettings.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Encryption/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-10841] Now disabling multi-psk for more encryption protos

src/hooks/Network/Analytics.ts, src/pages/VenuePage/VenueChildrenCard/VenueClientLifecycle/index.tsx
=> [WIFI-10849] Fix for client lifecycle finding all clients

src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/AdvancedSettings.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/index.tsx
=> [WIFI-10840] Fixed ssid and interface services options

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/LockedPasspoint.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/PassPoint/Form.tsx
=> [WIFI-10927] Configuration hessid value now string instead of boolean

package-lock.json, package.json, src/contexts/WebSocketProvider/index.tsx, src/hooks/useApiRequirements.ts, src/pages/VenuePage/VenueChildrenCard/VenueLiveView/CirclePack/Slider.js
=> [WIFI-11119] Fix crash on empty analytics point

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/CustomFields/NotesTable/index.js, src/components/FormFields/ImageField/Input.tsx, src/components/FormFields/ImageField/index.tsx, src/components/FormFields/NotesField/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/LockedPasspoint.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/PassPoint/Form.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js, src/pages/ConfigurationPage/ConfigurationCard/Form.js
=> [WIFI-10916] Added icons field to passpoint config

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11294] Now requiring ieee for WPA3 encryption protos

package-lock.json, package.json, src/hooks/Network/Endpoints.ts, src/pages/SystemPage/index.tsx
=> [WIFI-11392] Refetch all endpoints on System Page

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/Buttons/FileInputButton/index.tsx, src/components/FormFields/FileInputFieldModal/FileInputModal.jsx, src/components/FormFields/FileInputFieldModal/index.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/Captive/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/index.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/servicesConstants.js
=> [WIFI-11273] Added captive to services configuration

src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/MetricsSection/Health.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/MetricsSection/metricsConstants.js
=> [WIFI-11391] Added new metrics.health configuration fields

src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/Captive/index.tsx
=> [WIFI-11273]  Fixed empty services.captive fields

index.html
=> [WIFI-11455] Fix for .env variables in html file

src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Encryption/Encryption.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/LockedEncryption.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11306] Added key-caching field to encryption config

src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11294] Ieee now required for SAE encryption prot

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/AccessControlList/AccessControlListForm.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/AccessControlList/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/AdvancedSettings.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11491] Added access-control-list to SSID config

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11595] Encryption proto added verifications

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Encryption/Encryption.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Encryption/Radius/Radius.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Encryption/Radius/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/Encryption/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11713] Enabled radius for SSIDs with no encryption

package-lock.json, package.json, src/components/Tables/InventoryTable/EditTagModal/Form.jsx
=> [WIFI-11750] Fixed inventory tag config refresh

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11761] Fixed configuration subnet form rules

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ImportConfigurationButton/Modal.jsx
=> [WIFI-11802] Now allowing users to paste configuration when importing

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/RadiosSection/AdvancedSettings.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/RadiosSection/radiosConstants.ts
=> [WIFI-11803] Added allow-dfs option in radio configuration

package-lock.json, package.json, src/components/CustomFields/ConfigurationSelectPortsField/Input.tsx, src/components/CustomFields/ConfigurationSelectPortsField/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/index.jsx
=> [WIFI-11892] Fixed interface.select-ports configuration options

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11906] Added ssid name testing to configuration builder

package-lock.json, package.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/AdvancedSettings.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/LockedAdvanced.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/RadiosSection/AdvancedSettings.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/RadiosSection/LockedRadio.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/RadiosSection/radiosConstants.ts
=> [WIFI-11970] DTIM-period now configurable in interface.ssid

package-lock.json, package.json, src/pages/VenuePage/VenueChildrenCard/VenueDashboard/TableModal.jsx
=> [WIFI-12030] Fixed venue analytics dashboard table sorting

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/SingleInterface/SsidList/SingleSsid.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/InterfaceSection/interfacesConstants.js
=> [WIFI-11937] Config: max SSIDs per radio now enforced

package-lock.json, package.json, src/components/CustomFields/RrmFormField/index.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/Gps.tsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/index.jsx, src/pages/ConfigurationPage/ConfigurationCard/ConfigurationSectionsCard/ServicesSection/servicesConstants.js
=> [WIFI-12242] Added GPS service configuration

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/hooks/Network/Venues.ts, src/pages/VenuePage/VenueCard/Actions.tsx, src/pages/VenuePage/VenueCard/VenueFirmwareUpgradeModal.tsx
=> [WIFI-12286] Add support for new venue upgrade API

package.json
Release 3.2 version update.
https://telecominfraproject.atlassian.net/browse/WIFI-14165
=> WIFI-14165: release 3.2 version update 
